/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ivmdiaz.projects.boletines.tool;

import com.ivmdiaz.projects.boletines.tool.modelo.ConfiguracionCorreo;
import com.ivmdiaz.projects.boletines.tool.modelo.Directorio;
import com.ivmdiaz.projects.boletines.tool.vista.PanelBoletines;
import com.ivmdiaz.projects.boletines.tool.vista.PanelConfiguracion;
import com.ivmdiaz.projects.boletines.tool.vista.PanelDirectorio;
import com.ivmdiaz.projects.boletines.tool.vista.PanelEnviarBoletines;
import java.awt.Color;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;
import org.apache.commons.collections4.CollectionUtils;

/**
 *
 * @author idiaz@cx.local
 */
public class MainJFrame extends javax.swing.JFrame {

    private final PanelDirectorio panelDirectorio = new PanelDirectorio();
    private final PanelBoletines panelBoletines = new PanelBoletines();
    private final PanelConfiguracion panelConfiguracion = new PanelConfiguracion();
    private PanelEnviarBoletines panelEnviarCorreos;

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        this.actualizarContenido(this.panelDirectorio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenido = new javax.swing.JScrollPane();
        jPanelBotones = new javax.swing.JPanel();
        btnDirectorio = new javax.swing.JButton();
        btnBoletines = new javax.swing.JButton();
        btnEnviarBoletines = new javax.swing.JButton();
        btnConfiguracion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        contenido.setBackground(new java.awt.Color(255, 255, 255));

        jPanelBotones.setBackground(new java.awt.Color(56, 159, 214));

        btnDirectorio.setText("Directorio");
        btnDirectorio.setBorderPainted(false);
        btnDirectorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDirectorioActionPerformed(evt);
            }
        });

        btnBoletines.setText("Boletines");
        btnBoletines.setBorderPainted(false);
        btnBoletines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoletinesActionPerformed(evt);
            }
        });

        btnEnviarBoletines.setText("Enviar boletines");
        btnEnviarBoletines.setBorderPainted(false);
        btnEnviarBoletines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarBoletinesActionPerformed(evt);
            }
        });

        btnConfiguracion.setText("Configuración");
        btnConfiguracion.setBorderPainted(false);
        btnConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfiguracionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotonesLayout = new javax.swing.GroupLayout(jPanelBotones);
        jPanelBotones.setLayout(jPanelBotonesLayout);
        jPanelBotonesLayout.setHorizontalGroup(
            jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviarBoletines, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBoletines, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDirectorio, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanelBotonesLayout.setVerticalGroup(
            jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnDirectorio, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBoletines, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEnviarBoletines, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(312, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, 994, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contenido)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarBoletinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarBoletinesActionPerformed

        final List<Directorio> directorioList = this.panelDirectorio.getDirectorioList();
        final ConfiguracionCorreo configuracion = this.panelConfiguracion.getConfiguracionCorreo();
        if (!CollectionUtils.isEmpty(directorioList)) {
            this.panelEnviarCorreos = new PanelEnviarBoletines(directorioList, 
                    configuracion);
            this.actualizarContenido(this.panelEnviarCorreos);
        }
        else {
            JOptionPane.showMessageDialog(this, "Error. Debe cargar un directorio", "Error", 0);
        }

    }//GEN-LAST:event_btnEnviarBoletinesActionPerformed

    private void btnDirectorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDirectorioActionPerformed

        this.actualizarContenido(this.panelDirectorio);
    }//GEN-LAST:event_btnDirectorioActionPerformed

    private void btnBoletinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoletinesActionPerformed

        this.actualizarContenido(this.panelBoletines);
    }//GEN-LAST:event_btnBoletinesActionPerformed

    private void btnConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiguracionActionPerformed
        this.actualizarContenido(this.panelConfiguracion);
    }//GEN-LAST:event_btnConfiguracionActionPerformed

    private void actualizarContenido(final JPanel panel) {

        panel.setSize(1000, 700);

        this.contenido.removeAll();
        this.contenido.add(panel);
        this.contenido.revalidate();
        this.contenido.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainJFrame frame = new MainJFrame();
                frame.getContentPane().setBackground(new Color(56, 159, 214));
                //frame contains nothing, so set size
                frame.setSize(1200, 700);
                frame.setVisible(true);
                
                frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
                
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }


            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBoletines;
    private javax.swing.JButton btnConfiguracion;
    private javax.swing.JButton btnDirectorio;
    private javax.swing.JButton btnEnviarBoletines;
    private javax.swing.JScrollPane contenido;
    private javax.swing.JPanel jPanelBotones;
    // End of variables declaration//GEN-END:variables
}
